### ISSUE TITLE
Move/fork this to the primary InfoSec repository

### ISSUE THREAD

**Issue by dallbee** [InfoSec-CSUSB/club-websystem#45]
Because having things in one place is good

**Comment by securedirective** [comment]
It should be a simple transfer of ownership, but I think it must be
initiated by Alofoxx.

Kenneth Johnson
909-921-8097

**Comment by Alofoxx** [comment]
what account do you want me to transfer it to?

**Comment by securedirective** [comment]
https://github.com/infosec-csusb

*Kenneth Johnson*
kenpilot@gmail.com
909-921-8097 cell

*My passwords are complex, long, and frequently changed. Protecting my
colleagues and myself through good cybersecurity practices is my
responsibility.*

**Comment by Alofoxx** [comment]
I can't transfer the ownership unless I have admin on that account.

**Comment by securedirective** [comment]
Sorry, got busy this week. I just sent you an invite to join the InfoSec GitHub. I'll grant admin if that is needed, and then just remove those permissions after. Let me know when you get the invite.

**Comment by Alofoxx** [comment]
I must have the permission to create repositories on InfoSec-CSUSB in order to transfer ownership of this repo.

**Comment by securedirective** [comment]
Set the "Allow members to create repositories for this organization" on InfoSec-CSUSB. Since you are one of the 3 members, this should allow you to do it. Let me know.

**Comment by securedirective** [comment]
Thank you!
