### ISSUE TITLE
Nav Bar Issues?

### ISSUE THREAD

**Issue by BrendanHiggins** [InfoSec-CSUSB/club-websystem#58]
When on https://www.infosec-csusb.org/ the old 'TeamSpeak' button in the NavBar says 'Discord' as per an update to the pages.

However, seemingly at random, when vising other pages, like 'Wiki' the button changes to 'TeamSpeak' but still brings you to 'Discord' but displays the wrong label about 50% of the time on different pages.

Confirmed it wasn't a cache issue by Ctrl + F5'ing the page, as well as opening it in an incognito window, and on my cell phones web browser.

**Comment by securedirective** [comment]
So weird. I see it too. Will look into the source code.

**Comment by securedirective** [comment]
Here's my theory:
The site has 2 worker processes to load balance. When I wrote this code, I put in a global variable to store the navbar data so it wouldn't have to query the database on every page load. When you change the navbar, it clears out that global variable so next time it is accessed, the database is queried.

But I think that global variable is only per worker process, so the *other* worker still has the old navbar data and doesn't even know it.

**Comment by BrendanHiggins** [comment]
Interesting. Yeah, it's odd we hadn't noticed it earlier. I guess we don't update the NavBar that much.

**Comment by securedirective** [comment]
Probably the last time I updated it, we only had one worker process.

**Comment by securedirective** [comment]
I'll comment out the caching code, since I don't know how to have a truly global variable that spans python processes. That's basically what the database is for.

**Comment by securedirective** [comment]
Fixed by commit #b04c2ae52b
